# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libcheckoutsys', '0002_auto_20160621_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[(b'B', b'Borrowed'), (b'O', b'Overdue'), (b'L', b'Lost')], max_length=1),
        ),
    ]
