# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libcheckoutsys', '0003_auto_20160621_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
